# Generated by Django 4.2.2 on 2023-08-30 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csinterface', '0002_remove_part_created_by_part_location_part_origin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='updated_by',
        ),
    ]
