# Generated by Django 4.2.2 on 2023-08-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csinterface', '0003_remove_part_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='description',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='part',
            name='number',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AlterField(
            model_name='part',
            name='origin',
            field=models.CharField(default='None', max_length=10),
        ),
        migrations.AlterField(
            model_name='part',
            name='status',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='part',
            name='supplier',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
