# Generated by Django 4.2.2 on 2023-08-30 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csinterface', '0004_alter_part_description_alter_part_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='location',
            field=models.CharField(default='None', max_length=10),
        ),
        migrations.AlterField(
            model_name='part',
            name='picked_up',
            field=models.CharField(default='None', max_length=10),
        ),
        migrations.AlterField(
            model_name='part',
            name='price',
            field=models.CharField(default='None', max_length=10),
        ),
        migrations.AlterField(
            model_name='part',
            name='request',
            field=models.CharField(default='None', max_length=10),
        ),
        migrations.AlterField(
            model_name='part',
            name='reservation',
            field=models.CharField(default='None', max_length=10),
        ),
        migrations.AlterField(
            model_name='part',
            name='stock_status',
            field=models.CharField(default='None', max_length=10),
        ),
    ]
