# Generated by Django 4.2.2 on 2023-08-31 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csinterface', '0005_alter_part_location_alter_part_picked_up_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(default='*', max_length=50)),
                ('popis', models.CharField(default='*', max_length=50)),
                ('sklad', models.CharField(default='*', max_length=50)),
                ('pocet', models.CharField(default='*', max_length=50)),
                ('cena', models.CharField(default='*', max_length=50)),
                ('typ', models.CharField(default='*', max_length=50)),
            ],
        ),
    ]
