# Generated by Django 4.2.2 on 2023-09-01 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csinterface', '0006_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='picked_up',
        ),
        migrations.RemoveField(
            model_name='part',
            name='request',
        ),
        migrations.RemoveField(
            model_name='part',
            name='reservation',
        ),
        migrations.RemoveField(
            model_name='part',
            name='status',
        ),
        migrations.RemoveField(
            model_name='part',
            name='supplier',
        ),
    ]
