# Generated by Django 4.2.2 on 2023-09-01 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csinterface', '0007_remove_part_picked_up_remove_part_request_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part',
            old_name='origin',
            new_name='count',
        ),
        migrations.RenameField(
            model_name='part',
            old_name='stock_status',
            new_name='type',
        ),
    ]
