# Generated by Django 4.2.2 on 2023-09-01 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csinterface', '0008_rename_origin_part_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricebid',
            name='part',
        ),
        migrations.AddField(
            model_name='pricebid',
            name='parts',
            field=models.ManyToManyField(to='csinterface.part'),
        ),
    ]
