# Generated by Django 4.2.2 on 2023-09-07 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csinterface', '0009_remove_pricebid_part_pricebid_parts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricebid',
            name='company',
        ),
        migrations.RemoveField(
            model_name='pricebid',
            name='price',
        ),
        migrations.RemoveField(
            model_name='pricebid',
            name='starter',
        ),
        migrations.AddField(
            model_name='pricebid',
            name='customer_type',
            field=models.CharField(choices=[('RG', 'Regular'), ('DL', 'Dealer'), ('GR', 'Tajmac Group')], default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pricebid',
            name='parts',
            field=models.ManyToManyField(related_name='parts', to='csinterface.part'),
        ),
    ]
