# Generated by Django 4.2.2 on 2023-09-07 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csinterface', '0010_remove_pricebid_company_remove_pricebid_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricebid',
            name='company',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='csinterface.company'),
            preserve_default=False,
        ),
    ]
