# Generated by Django 4.2.2 on 2023-10-13 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csinterface', '0012_alter_part_price_alter_pricebid_customer_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='price',
            field=models.CharField(default='None', max_length=10),
        ),
    ]
